### ISSUE TITLE
Starts too late

### ISSUE THREAD

**Issue by mikulik86** [TommyMaes/SetVol#3]
Nice App, but sadly it starts too late. I need it to set the volume right after login.

**Comment by TommyMaes** [comment]
it is possible to run programs in your start-up folder in a serctain order. I use this method myself and works great for me.

Press WIN+R to open the Run dialog, type "shell:startup" and press Enter.
You can put all the programs in that folder in order by beginning the programs name with 1_ 2_ etc. So if you want to make "SetVolStart" (which should be there) the first to run, you just change it to "1_SetVolStart". 

Also make sure to run programs that automatically start making noise as last. Mind you that there are more then one start-up folders. A program in a different start-up folder might ignore your sequence. As far as i know the shell:startup folder is the only folder that will allow you to put things in a certain order.

I have not and will not make this an option in my program because it might interfere with the start-up order someone already made and because there are programs that ignore the order because they start in a different way, **therefore there is no guarentee this method always works.**

Also, if you really want to go the extra mile, you can use Task Scheduler to make programs run even before windows has loaded the desktop. I would suggest google for more information on this.  (also not guarenteed to work)

If its the windows startup sound that is buggin you, use google to figure out how to not play that sound.

Hope all this helps you
